apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:S0aWb0ZjMk6b4g0ctOUZ3Wkh7ttQEuHe/qv5CimDnf1KmZuzunwhNg==,iv:6xKhJMSlRewF14XLikRZH5+O5+BYZeouZsorXj5l6q4=,tag:A9Hc+/zZmejPODD3JBMJYQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wfgvl0rk8kkxwj5vvhfagu6lqc3d3vkfv09vtudjdz7qq9jv4fessz58wk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydXlNeC9KbHhTMnc5bkpJ
            ZTJNNDF1TGdHR0hSdU9tNTd5RWFoSEhhYVZvCnlUT3l1a0hFamZ1RE1pWUQ2a0pO
            ZENDQlJnRmpiZVR3RUhwbXRwVS80SlkKLS0tIFQvbTBYVTBKRk1oRVE2U1dLWjRL
            WGR2VmYyQnVyb0d4YXZLb3IyUE14Uk0KnhWe/4697JP8ff1j81wGMNyY2Gzzv0IB
            ZKtyTsfEMsXHYy5Zmu13zWVPeySLVoxiuI+AEcjRt/SAakaH0LYbsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T19:24:36Z"
    mac: ENC[AES256_GCM,data:3At1KkIWfbH+y/ml/f+YDht50O63uMtLk3RX/RCu9oWV49K5QhTOT/B9P4gz3tK/brBdM2wZn+h6M6uJkkEfCeYhMyederGNmLVPpkopq0x52ZmZfoGgTXj9i66gfOVtVyAWFlJf+n/jevKeR0pn982dAO3ONk6keIVP85t6tzg=,iv:FacWJ44WE6hYqe15ZnoxeyccKMfzLEz7ll9ajs0cDy8=,tag:Zz76eqondERgKGHDqCF/MA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
