apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:rMKIDZDkqMbC1duDIUGhAeg/fbjLl4Z9cI1N6jm62wYBwYQotL+PYA==,iv:UgE6xI09fk+L/Z31rnzjJ+2leoRfU+aHCuq1vND6F70=,tag:c1jVU+PPQHy0dnoDUF81RQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wfgvl0rk8kkxwj5vvhfagu6lqc3d3vkfv09vtudjdz7qq9jv4fessz58wk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYWF3WjlLdTM1Uzl3Y2lu
            ZEdwZHhmVnl0WjAraW93SDVoYlF3allMZFVzCkV4Nmh5TFBZMHd0V09sSTFtK3B0
            ODNNaHpCOVp2djFWZW5Wb3h5Ym5RckEKLS0tIFdObmZud3RlMFNiMUt0OHArY0p3
            OHB6dGVDdUlZMTdtWDNzOWgzQUl2bFUKF4NmBt/PEN8Uog8xIr2efFCOvAgLlbxs
            2Ijw8NtC3ndJ0RFoVdvdICsGItx4MQUgd23pAf/zrYqbvq8geX+kPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T01:22:39Z"
    mac: ENC[AES256_GCM,data:qISO4wTpFjO0f5Zvm1Q3VdTfP4JuJaIqv+Hu0gIJ8exPlN3xdOBOKYIeXKCjESj/WhlxynwrPpOrD21APMDmpWlKBGFMpUvp+CRFUl/kiFdJX7m1ZZrCw57xIVuBM+egkhhLCj9Q9sYhK+uD089cpjtVFuRs9NwEfS+Ya9ZQjeg=,iv:GIYvoXlLOMjChvLrrDpQg1CTzcdxBHmqoa3ouNW4lUs=,tag:gDDqkxnI2OpOW8UpHEK0Kg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
