apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:cM7TsrP/UUDItTa1dlU+1HgoIdYAxIz/ajSIS9x6961HgjreR4KrXw==,iv:nd4q/8TfZ/rhy76QB9UGjU0rlc/TMu5OQ14Mxbt7NDA=,tag:7ybuZu8LRgnPmP5EfN/j4w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wfgvl0rk8kkxwj5vvhfagu6lqc3d3vkfv09vtudjdz7qq9jv4fessz58wk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISFQ5bjlZRmpZOExzNHZK
            OHNvcXBuTGIzMkVWUVBoUHQ1WWJPUnpCMlRrCmsyV1A4T0krMW1Ea0NTNVgxODRp
            NWdWL2ZPRDAwNUliNkoyWlB6aTcxeWMKLS0tIHdaNkd0Qmdpa0xDaTZLaC8zWk5I
            TmhCY3V3a1M2UkQrWkJuQ3Vpa2tJUE0KUEdI9A7WVDpyI4FiCNqcHDHmRfqdWtlC
            Bs466ZV/QdxNtJDZes111PpXh6ClYh2CUbquY/IejHANb14wfcONQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T14:42:06Z"
    mac: ENC[AES256_GCM,data:YuSPC+glYZJf//Jlm/gW/frfy621UIgceN4CUyjk5FplFYGOb/9SXan4sk22se3H61ECq1ozmxUqFdYl7FEGnD07XiVlvDi7RdSOEfA3R2/o+9g8hTXokq/oL854bxR2MllGEY8cgMOtMFnWoHOdcs2g8DScvIRSbjFomB9CibQ=,iv:ok4uZh5GVrq2h7o9RSuhLuDAUb7oJwX6wm+R1QITTF8=,tag:TMru2kPNPWdlGidm/5ro9Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
