apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:rwI0eYcw9xm/Z/5M+eIvNTmitfITg6LahIYPb+pcvh4jNmIKqIOBvw==,iv:CunbavvQzUoILx3BhvUuZRX5qAdwMeksZvk4OS3vGFM=,tag:nPQhaNsLSKVk/1j7JeuhBg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wfgvl0rk8kkxwj5vvhfagu6lqc3d3vkfv09vtudjdz7qq9jv4fessz58wk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbmhXQS9HVkNpT1p1M29p
            OW8vYy9FSXF2emJIeGhFWHJzcHljYjNBYnhNCnR4dlVsZG1OUGRHbUJUOUF0K0N5
            cE9sVFJrM3BhVGZFT2xscUJZazhRTTAKLS0tIFhqdnFXSzYyNmJyMk02SGdtdFVS
            T010aDA5VzVnTEduRThXalJFaG02K3MKighr4bhNakZfhqEcnCgjgPT/HkbIpIBD
            fl6FCjcQ0GEZnErhbwufgJX0p6aUJEA2cWaRaFVCmM4GB7fe36idpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T15:03:43Z"
    mac: ENC[AES256_GCM,data:s0QCGDXMHGbjaFFPUTDEW/ZmTpk35plqNzzMfZ0Eq2LJkAbb6hixm8TIcMnqP2mCXAEEA98ToNmUHLRSNK/E8dvjf0KrkeBT6Btr48p+etjMtnmvE1k6tKt43e4+IBw9pfOtrYr+YZ/rseng5cyDCLiCPoLEQAEfn8emisCJgQo=,iv:IO5VGdPTvUcvpm7jKqHH3YtzXn19NxO2tarTHRaBAFw=,tag:PRRMfA/B0NUVXZVPb4X7rw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
