apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:UT0DAb7f9RE+zdp07DvmaxbGk6NCzlCcJD/GYXeE5kPpx0sDwraB8w==,iv:TzaNC11RYQSEKkBVaRKXrn7UVg/CAqKYzJWlbI3koHc=,tag:T0WdXa9Kwb+TsJwnZf046A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wfgvl0rk8kkxwj5vvhfagu6lqc3d3vkfv09vtudjdz7qq9jv4fessz58wk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTVdLdjNzYUZza1N0Y3JZ
            TlprSlZQYjRuenU3aUh2b0lGNVRhZG1IemtJCnhTZGo3bmZwK3VoT2t5OThGQ254
            eG5pdlJCVXJqeER3Skp3R2JjNVFJa3MKLS0tIE1NbWQ5b2pVTm15NlNRT2FUM3Fv
            ZG5CNTRpRjRCM2hVMGNZYVBLcnhNNTAK1U3zZdTbzKn6a6kYY4KDZDsUjZlR9zm/
            mhwWSt5KpqjI8n2FH6FZy9yAoyPJcpk7ji5SEwShBSrlOAt1AyGYUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T11:12:48Z"
    mac: ENC[AES256_GCM,data:X8Ts6lJIr2hAV9yzkL1QS09UexW52GWTypnwB1nHQYTieIMEHznbSiVNNoaf8BOYmQPMf1yCUGzyjP4/ILBFsZ87aa9mcX9RUmQoURksZquYa+f1RAInwQeeBBSkDuv8DkwCMoG8gLm2+qott376jGxZWQHYm2fI5gLeB1doFxc=,iv:vsV16MJtK6wgsJYduY59CDRf0WF1osv980GSvTZYLBg=,tag:3tXCcHp5Tu0O95ohD7riJw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
