apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:qhCxpvn2NJ83q+W1XtGbZokhv9DHrf+r6fELon3LZ4XNa3yxR9h+8g==,iv:cIAOYzyV1cZDl33LOugv5g6tjXCaIVixvXi3/yxPmFE=,tag:6ZOA7eUqoKkYwzYjQtQL5w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wfgvl0rk8kkxwj5vvhfagu6lqc3d3vkfv09vtudjdz7qq9jv4fessz58wk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNa1BxOXBsU1RNNzZXUFNl
            N1MrZUwwOXN4UnJGQVNVOW1rSWJPa1ZxMlRBCjFNcENISnNITjFvRDhnVmVzMXpQ
            VURvS0NuWHhxUjBndW83d2ZveU9Nc1EKLS0tIGNYWGl2b3dGKzJmMDl6aWcxVFhj
            YSt4VWU2WGxpWUZSc1VQa0ZzVHFUZEkKXALYYAjn3aCz+YnglFz9eecpmHii/jWM
            wEjXQHtwWe/e1sql7lFYjYpA8gW27c6i/hwGCLX76ggipRmFyB5gxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T01:58:23Z"
    mac: ENC[AES256_GCM,data:su9mOVIGUh6J2wUmqID4Yhs7s3/4a/oeRPVEURDsmTgc0GrdYYRnJCQjufdlET7i2DcUoizX6t6zYOz6ZYHdG6egRI5CxDR6qOd3o1qUquXTKCwu9EwPm1/Hif3cVLmnhw2DkGG+0CKdGl7RDZ9k0cfRdyK+73BR9V4W5b/WY9Y=,iv:EMBwUZPFmRbduHUxE42GNniGgizIba7vUWytSV/JhwU=,tag:MfwP/f3pE2XUNTzIHRJCGQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
