apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - audiobookshelf/ks.yaml
  - ext-scrutiny/ks.yaml
  - external-dns/ks.yaml
  - gatus/ks.yaml
  - handbrake/ks.yaml
  - home-assistant/ks.yaml
  - homepage/ks.yaml
  - it-tools/ks.yaml
  - jellyfin/ks.yaml
  - kubernetes-dashboard/ks.yaml