apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ww7IpPXzrJSe+xYf/vEDCLBS04rm+opDd3kXNBteZlK00xj5SMUHp1XSUSLBsJ4djRlYUOTlrfW1ZpPa79FVqI9MZQGJ7M1dfw0uEj2mjraqM2Ul01OSSz7AcNRqv4lTmNBz/Q3mP2S5uTyUPe7JWIQxDPb2c/XmCqSjp9A/nUfJ4wG2BShgv9ZQOYnMB16mb63hKW90yiuOtGU37u9F9lFH/B4ehMSDlO39k9TlZGBAb9QYAgnsAITVeTJQ2nMpO8TWZPSCvaL4LARBOej8eu/JJGXwOWcLxdqlEmxoZLHAgNPaTD6ybvCf0w+GEW1KkuUQ7SwF/zSpqsZ190ztZiRPWjPQrrQ4WFA/6Qo3AFwqXdhmz4KmZwJM8BGI5fDF,iv:/IzRSF4qt+WGzGBzcRQ/JnTIFNEXATXWuQeKA2LiiYY=,tag:JmJEOBltm1DdIT6ny2SWNw==,type:str]
    identity.pub: ENC[AES256_GCM,data:SQP+jL5SFg+wWkWRQipcsyZe5uVx92ntcK0XUZtfLf/BX0/14ry2JQNujyP+zzkDAmOyQPhu9+ZcaHF1V8WU29Q4OwJTzxX5G3M0edZP7c6d7Nz71WhTw4B3ajHX7DPL3L8RhK/b/05t5Vbt+HswUdj7bajHd84hTVfQzEt163unlmZ5nG6khjU4A+Op6rjW6i+AC6YSd5CW3R7A+UFmyKN3S9oonVYKZhYuHu1/swe5nnLTjL8AiwovGF3XbuaC6Hixxd6GNu9z5512Rw==,iv:UJRorzXV+fix6vI3LOuCjg3jlbj5gt97Z32afT5db/g=,tag:yIvHNQoySAqU4FgoIDdsXw==,type:str]
    known_hosts: ENC[AES256_GCM,data:+vhOa7RY6ymd6r+Gcviep2o22xg41DveQdyuZ8n7UUqD1FvQBvHiPDuaM+9/HEjvz6qHzy6xKwa3v/wJSzKAOhKQHYVqoPR9w/Rw1j3E4YF5GmwAXlLk220F3G+EOxEJJ/2Tpct3bRCMJqzfk8GMBjTtDbKCg7Mmn0IvW3lKpxn4zayqdaeKvtskk0N7sXsdiLrK6XnwiC7BD79SCaylbSno9609/UUtFTnL,iv:epwQZwuS9I97pRWppMgfnPm0h7eu2WcFLOSVT6XHBZw=,tag:SxWGO8Y4egWwvBocgs1QuQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wfgvl0rk8kkxwj5vvhfagu6lqc3d3vkfv09vtudjdz7qq9jv4fessz58wk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TmVxeG9aNkxXcG45YlYy
            QUtBeXdVZ3ZmbXVha0tCS1ZYM3dDUFErd2dnCmZWS1I2aWRkbjVNZkIrbU9TcFg4
            VWJNN09rcHlMNWxaUlpKcXlrRkE3SXcKLS0tIHN5eVh0UkpvWXpmajlDSGQxZ0dm
            RW1rZGhXRkppTmFUQTZMd09nZ1hUSm8KeKw3yajvC7NpDwbAhVGHOmBIXs6chiQb
            pJ9P89MGHjYzYZPEoada3eUwz6unoEXFaCnrx2s8KZ8BHSE+kTIUcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T09:04:20Z"
    mac: ENC[AES256_GCM,data:76ev3l7EedDdQeMEVuQBXdsJg4CvZ+iJ2QsNWOyyjbsNYvURy2aZe3GZVqFL2TAc45YunVHYUK8YLe2ycCedcqPmficDot8cAaTLtsZkJ+Ee5RJ83cQiRTPSBokKJWbiu69AoMzLqmAieb1EvkVD1/GMXqZ6nu4BZT5c5adAST4=,iv:AKXFEJD002opOHVx4BBQaot175WhAvf6AphWXTbEFMo=,tag:A52SNP03/Gb+735Kj/ympg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
