apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8M56tFQz8JtTxJOFvrrWgfnZb5yw2MJAfRTSmFV9X7fl0lcXOAbkY+Vw8S8uMJMxac/QDyv+3HjXLD1Wo2Gt5ZLIg62xeED3cXtqefhC4w2frUFSlw80yCrqLbuxkD8TLMWFQ+1gt+lQhwyBOEn9n40FxVjB8EpyN6Bbd7RFYZ9ZyBXcpcfOjL0ujP2gmt6aelp6I2m2QoI5nsfRUKZNB1H/h4ctQEm8CIt2ieWKNogpFh5vD5Lievbxw2F2gxEwT5OSg7RT0bN84YTdjH8r4DEkXP9kD8d830/dsWY3GDXFe6Gi6QERY7tBTVPpIdEUG+gOjQnGR1G1ygUHpkAptQpFDuTpIBWwS0Ant5EsjigBmWhL1gPOF/RAt89b44Vt,iv:K8FG9JS6mHnTWJoOoU3VOuOfLAsuM1xu1ouB1MgL1O8=,tag:MSai7DlscBTwebyLXdAHfg==,type:str]
    identity.pub: ENC[AES256_GCM,data:DTE8R/sUXTtet/iVT3K8bf5kf1iaPOHtHLZM0eAr+kBFc4B1NLo1NK/WQ0735Lmuii+ZwW0D22BPfDA1SUQfQ3x/hiWa5F8pTKN4HONwCpkeMD+vnFBrZkF2eQmeEm6+/UNble3un1IIIrb8TF7eOqqS5+l9mERTq+hmv2Wh/VHednRF6JHdf1I8ofn1MOb22pa3a1WRBzbeWc3sqeZbayTF1My2CLsMFJPMRRsJG9XfrtY7rJdHVOLSYa0lBwUb/ETvyBNeqv0xn+KZLQ==,iv:9I2gRrq5oeyuDTt94uWc0/wXeFZPk9ZCa2ZyTrp11TA=,tag:PRJVRj3sFPNG4AJZpf2PKA==,type:str]
    known_hosts: ENC[AES256_GCM,data:X9vMGvZNRBUbcgeRYfKkLOa452+HbkyPuhfjXjZhZ4c4iGrLJCQI0QZJztdIPM9eI/cK0XugUXs7YYjjKohMRNLOAG+DeCRU5p9Qr4iL23hL/ULPdPrKskFdecTeb/KXvMYYyBd4xk/T2m4iqkK2fdHU7oMI2mxyxuE+E0eZDr7hnXDkpfNmvkqzee0WjMNjJc4pGI9Amror3xfbOpJZcne2fxgB53OKrGMn,iv:8tFxfTgN6Ea8t2fqKgcNApdzhKUq9QCLRarRR+NmjLE=,tag:ewyWGFiQUWsjEu76OckIdQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wfgvl0rk8kkxwj5vvhfagu6lqc3d3vkfv09vtudjdz7qq9jv4fessz58wk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdEJ6T3Fla1AyUUFlMk0y
            QTVpZDR2cmN5aWtMUFIxUkVqSEpvYnNZRkZjCjlWMmd1L2JqZm9YNEI0MS9DRVFt
            TkRXOVMwdk5aVDNXR3dUSkoxQ2RicGMKLS0tIHQzVVhPVzhQdVAzN1RxUGFKR1Fx
            YXhLaFNQeHlScGdmakdUK3gzaFNGeTQKrS9t42fMdzNGPzxrHDaSesWHlnrBVd9u
            jXqW+JjRuqOGhGCSnK+L9fAmV1Q8AcpHkKFHEo6s+WEAy2nVXlIfXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T19:24:36Z"
    mac: ENC[AES256_GCM,data:zAlZ3X+eHotBevwqbMhm+UQitjDd/V1lX/gGDa6zmJ+4d077/c/j4FYeWFxii+ZSYlz2/cAUE7oQcFrgTyVvEYDszqYZafLyQ+Gk9YtfPs+xsNw+8OE/CyLqeWt4x2OW5fmX6nt9idQccvzFs7s0+8O4Fg8VH0Z+TWAiPQYQiLA=,iv:Sf1D+3GZTFmjmUan0abCqQdb9kCu0FsyN7oNEl9UUbI=,tag:f77GqsGXpX9mnWg6tUd0KA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
