apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KnaDFRARkTzZCLi3xbhzf5W4fqEwr1MINFmIZ91xZGc/2/7fW0QLpy712jl8FzkMw0XosyQjGSkN9uQplorHW43xJLpvZJe96okAfUzgf5Fjarht7xH7SZCeoeqP71QzIP/hJoLyNhzPhD7PxF6iXrnLYsF6HOdXXKQo4G4TkvcUtBjlvFtqCDXZasyIh+T0KGor9Lf9YJVy0wYW65qLD2Qcam583jY+DzqK0SgorZ4CIJWoBEzPoVHQEutj9UVEC8uGwjY/TCjzgrfYyQ0dn1oBkAj79nei20FJCgEfpEA3ne69t17+Jzc1+N871okJggXuwux+EF1zJWsKh6POjs9M3ld6dXpdloIT909+aVK+YMWqHW5QB2am9qTTSKlq,iv:qNrsTV3o+cq4rWuerNtJ5y/jsiQeiCOntDIt65RInl0=,tag:PQL2NgeAQexzsrqJtBYjLw==,type:str]
    identity.pub: ENC[AES256_GCM,data:b7j9+sDaEyBMYQHMpZf07VsCsMm25mAMAWj+aTtKTknSzONahKgAxvwIb+tYYILxgWYywsXPMITLdDRsA1Bbz1BuryinVmhcviDWLCf3zpz/xmjYlgyvhrOFSRwocx77jlLnlsRc3gCW+/raj4GcuRvD9vZPVm8ORANh07Bc7/urQwtdTKDUaCDGFH9oYeh4l2TVufxwGV3l5/Z0bogIc/zndNRTU0Cj4dgY38XM2KbIQu2VEmNlHZ/4PSMZInWycpb1YsZ42gTOWejHbw==,iv:g1T82RLuwQF6DG9a+KzU08E3/4mqTXp286U9pytjUmM=,tag:kueN4+V2Jqsyu6YW8L5QNA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ETjw5Qzjl6y8xeEqyMS1qJwWTKkB2BZQOJ6eDpmgAvPjWc+czWmusg/ck6tTxx8tj5NsdMMXTWYu0iMCVKgKunjkAk3F3SxLnz8Kceeo9Y6JTWmzRldfcIwssuv5uPv7jwzDUMGy5xsuSziNn0GKIvg6y+UKl5uwGvd7T6ASXWyuwWK8/C5tEY2XSZ2RZPDw9UHyUIQ6VcfLF4VOTEDHpCV8k/Ccnsf9y22K,iv:vfP+pNsyEpuPoH0MNRAioPZyy23MD/YHRHTBS3etqMk=,tag:/q0wDENOimumGUXMAvPAuQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wfgvl0rk8kkxwj5vvhfagu6lqc3d3vkfv09vtudjdz7qq9jv4fessz58wk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZldQVFh2YnlQcFBIZlVi
            ZmRQTUNlcUczendXQUxBSDM3WFVBVnlUdlhFClRXN2ZlWGlsdTVXNExSVkh4SjZH
            SzlnZmxiR0Z1MW5odCtWM1RjZ2JGMUEKLS0tIGgxcmF4VmdneUtzYTlKS1NleVVD
            V293L1ZlM3hXSTVNNWRid3hsM1pvdXMKYLLWZ25oIBOntsnzmGcAflWLuDtrSJlc
            sf4ob54FBkZbZi16MmgFz+o/y0z7GIVIMoI9lurK1ELJXB7HpvGSug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T10:43:42Z"
    mac: ENC[AES256_GCM,data:/9J5CRkJHqc/AxFh/CrdYjLPjv3ousjey6vGHMAj57zKl0mnc3ulOBne1WDdGAG3ObTm4U7nrRGoksxpP0fKXGoO7GgrGE0p1GfAynjVGaNRnu9MTuixbn8XnIQFv009MCKKapIAQrdDpREZoLycNHQ8cKjIE+gS72ofdb8GORU=,iv:rnWieiN+Ke+HhowO6su1G/z3fLQLBSPNVw9rzRnfOCU=,tag:5Vh5o+MyLhQ75jAObAkUCA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
