apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IPsqngRwxDWvyS+nExcsaZ/hOAdu+jGeY2MqbP1ZmqCbV2c7drzro9leiP7b0WX6djEOlaJBhDtFI7E4HnCOjMirh4eieBBaxOLKZPAaM7v5JaIdu3vSKkL0ni4/71S4Gytt85VzRpWjAQD6D/9ioL2kRrWV1BNSLucz0P7ymC+XibqzNihIiTGpVDgVnRjQlUGuaryO3ia3QiBMCvnP/V8h6p2yR4g8BuqKMEps2jGNA0R8B7bq/DxifDS6zAgrvm1gasfxmWAaTx1C+UbW8LtQVx8GSaulh6hkKU6dOSKb6pikLU5I4+0AufgMU4FQRL9bndt/pDMSUXlyrlPJVn1mQ7tXk/vsyKexkkCke+NImLwlwRDw9wPTEUm5yNOt,iv:4KMxnzxMv05NDqJgJJsMYZIFlR+1WJZcCrMYdB3LoPQ=,tag:+CZDBU0YKdauA6u+S4U0MQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:f0Kj0dmejePJgqo9X36myPqFcOiqR2B8nnOvYx2CKTbwA46+Yz60gTucwxjQOLpHKohX2Ra1/Q+WzaRXi+vE4jkNujAgJp0ekWn6iCyboeI4mU20Yz0j+KAhq1XRVUv0MruAqqpeRakrsrXUMeXpHulSvm8G1huza+qfZ8OXlojTVFoYQ5dDGhghdUhWpaUWdk70fjKCshHPZxn0Zk8s2RdqH53ZbkPZxpEGC2m0lF38jrVHtYksA+bV8i+Klxv2h15Gy6Kv4s9E54RrhQ==,iv:MxVmSzCvwmne9++neJHErgCPzASsJuTreDkl/vjBHQ0=,tag:L7RfVfRCtEFnSHvxKu13Mw==,type:str]
    known_hosts: ENC[AES256_GCM,data:sZZlfOzIhMb+Qa1NFq5xU9ao0Vwa+d0awLB5JvyPbBzzOwwB+kn43tENy1Es8V7is164ckEQv4FP/HF4ICpSH+SUMA51Scb/u2bv8egNVEl0d7ol4IQ4c4WidDNT3Xu+ukGCTppdAc7OMEGlJo658x+ImiqerMAPm7fJ25/2jU0J7CAnlsZhBdSKcih41SbmOsET26YQ5abS9iSrfQTxgI/dxIhEMCL0yshR,iv:fuYNC4ThX5G5606+/uqipbovwJUwn552fOwraHbDPaA=,tag:wgwHjb7e73gwP6/nPS1+3A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wfgvl0rk8kkxwj5vvhfagu6lqc3d3vkfv09vtudjdz7qq9jv4fessz58wk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSkNpL1ZQdUVMc3c1bFpi
            R3NGcEJ6UTJ4dTBvd3BzdmdBTFgvR2s0TERRCkFSVWxZZUh3cEtZMk5Ya3FnSVp1
            b1JSRXF1aFM1MDUyU0hTN0xodUt3WEkKLS0tIHRyY2RySXZYaGhaTEMvQnRaUmFE
            ak9oeUJUWUJXaDZvaUhadHpKQmdNSjAK2Jh9n1i86D1nmnjdaRzNWXFhKRdCNRdd
            Ril0gnOUgeScPb0QaJgX3B4ucTg0U+RqziLDEp4BS8ISKeYySo8qKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T01:22:39Z"
    mac: ENC[AES256_GCM,data:6JPtq1OqIPLmWjn+WnEMikRqtjTSRjAI3Epyp6dyiLZpPOYWM6UiiWFzDyfNaUtUNVHazfQPTXenFMM0z+jtTKl99yBcG+JX+NxvKDRmQybkLqHiJU2G0blVNHWuDyyBWHOL0sqCuFFHds5sEFux+IQUSxQTNlMwFk8nPZxkI2Y=,iv:zI1WfQVgrUCOPSaZCX99e94ogRmaiQXSaVSLL10/2h0=,tag:C6Zut0GZMhflsM2SuDD4XA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
