apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xw6sJpALKfoD7XrHxEoePr2FTGoXmaiXhwl251i/ROn48KS0WNA0Rms6qR72K0yTP0jIGbUPlO3pLDfkb389M4U4T5RQNztaZhXqyU24hJjt5m0qK4TnsUk144Dz0dYJxMRQIPFrukoW7mXjb582IT74T6UL9oZ7CdCKu9EoyKdhH+9GcrSwxXC3I6FDIpKGGM5kD4xdf1HUU+WUhbSIeNe/W51dRP8A3Qq3LxJCw16tV9hr/K93GihqUB4dMSeEgt78+ymYpJ4edj5BDLaGWNrRo80ZTogJctD9jFQoDBm8BXJ1NJkfoFok4nvqsfzanN+twJoH9ScDP0BdZlc9hKJnyhCINlISxUY2cO1k3H8dbIP5mEJG57S6QG9DbTRF,iv:4dzgnmPcUIwbCgeFuYIprMeDxvA7gFTzxVcMaZ1f338=,tag:kthhK93T1Wg+TYN0I2L2EQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:SnTL+RJPyLssNLylmY01wLDz6lAn2mwfB0kGc8FwjWUPRtXiwOdMUvROALojd0SxegPK7bByGPZph9HgrsC1g3fffe0WLZAnpKBBXnPjsqu7U2dYvuBv+ohCOYx9THE6AdsVV6gTjZXG+31O6ee31ffY7XFb/ObqtHrV0KuO+7i6TuNi0DRvTZi9lHDm+RZnK/xmdWIlI86HZ390zGP2CjqLe/bPtu+5Dm22P7qH5efqUMreznQAtJwOyRG4JOUGWNr87MrGguMIWB2a3Q==,iv:VJhYecIO1eID+SEZFdYo9X1t1uxcU4bvGEzlt41GJj4=,tag:xgTdcScr/yllcL9UQ1DyKw==,type:str]
    known_hosts: ENC[AES256_GCM,data:gqbhkcG6F4tV2oIOk4inG5U5w35iW+ihKxnCscx7POSZ7YcVBA44DTekFqS1fMuxsZX5DAXirE6S3wSR5NMWp9rXFIgBN5unZKJfF33OhsSU5fqF5dLbeTMZxChlMRQywz1kol5xEPvJSTr6mHO9/mgS/IIlb0tQd6K9CmL44f+NP2GLK2R2k5F4UtOdBiPVi6jVNCsLwuu/GEEwo3VVjPM92IUcjzFPehu1,iv:Le5Pr62uQgJuN9GLiwk9dxeWwnfVVVDLZOtPRVqxiqc=,tag:ZaM/Q2Rwlhbd2FxwbYBr1Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1wfgvl0rk8kkxwj5vvhfagu6lqc3d3vkfv09vtudjdz7qq9jv4fessz58wk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYktjS2FnTUhRd0g0ek1t
            RDNNSldBd29MQVRSOTVWNVI4V0xETWdqRVM0CmNEUkZtNm1FTjNvM05odFZFK1JI
            Q1VqTHVXTzRQRGMvSVJGUnJCYkp0bkkKLS0tIFZ2YVpXN3NhZW9DU21KQWpyN3VN
            QytFaENzVXp6d2ZGMU1veUhsZlpMQlUKgh3DvYwZuq3EcvNadS9DkJRrUVpLYKvc
            bWLTP2nvV1GevCcpdzY7bTGwnELp9xZZMAdpislwAUxKoMus7u2ffA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T14:42:06Z"
    mac: ENC[AES256_GCM,data:vFF8Kg765gGbnQSKFRfQ0w7GYo5NWRVIUI4zKfi92Y2ubUDPSOQrMiqbxbfCpHBOrWf7vH/rJLeHx30EptcDV6AW6bZjFiLMlMSVLWlkMjaGtxObJbeuMLYSrujkNY1AHNmLaIPTTZ/C/Hu6JvjckjmtbfdUivfLZr4/ICIid7E=,iv:9wJGIstwdF2eC6E2jxt0yOjhhs0+pXyMobeWJbyj8e0=,tag:mp0LwW+Zi1QuXx39DFJtcg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
